# Generated by Django 2.2.6 on 2019-10-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191021_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_cta',
            new_name='banner_link',
        ),
    ]
