# Generated by Django 2.2.6 on 2019-10-13 22:11

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logue', '0005_loguecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='logue.LogueCategory'),
        ),
    ]
