# Generated by Django 2.2.6 on 2019-10-21 17:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logue', '0008_logueauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logueauthor',
            options={'verbose_name': 'Logue Author', 'verbose_name_plural': 'Logue Authors'},
        ),
        migrations.AlterModelOptions(
            name='loguecategory',
            options={'verbose_name': 'Logue Category', 'verbose_name_plural': 'Logue Categories'},
        ),
        migrations.CreateModel(
            name='LogueAuthorsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logue.LogueAuthor')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='logue_authors', to='logue.LoguePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
